# CI to Build and Test Java based on Maven
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ubuntu-latest #${{matrix.os}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build Maven
      working-directory: student
      run: mvn clean install

    - name: Run Tests
      working-directory: student
      run: mvn test
