name: Code formatting using Spotless Plugin

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name : Fix Formatting
        working-directory: student
        run: |
          mvn spotless:apply
          git status
          git diff

      - name: Commit Changes
        run: |
          git config user.name "Vikashlb"
          git config user.email "$Vikashlb@users.noreply.github.com"
          git add -A
          git status
          git diff --staged 
          git diff --quiet || git commit -m "Auto-formatted code!"
          git push